### PR TITLE
Fix TypeError in HiddenMarkovModel.from_samples()

### PR DESCRIPTION
**Pull request by fortiema**
When using `HiddenMarkovModel.from_samples()` with `DiscreteDistribution` and passing custom labels, if name attribute is left to None a TypeError will be raised from the concatenation with string.

- Cast `name` to str to prevent "NoneType + str" TypeError when name is None
- Add test case to prevent regression

### CODE REVIEW

**Comment by fortiema** [comment]
Any idea why the appveyor build for python 3.4 fails?

**Comment by jmschrei** [comment]
I haven't seen that error before. Quickly googling it suggests that there might've been an issue in Cython 0.27.0 that was fixed in 0.27.1/0.27.2, but we're using 0.27.3... I tried rebuilding the PR, let's see if it was just an anomaly.

**Comment by fortiema** [comment]
The plot thickens... Seriously I don't have much experience with appveyor and Win builds. Seems to be an issue with the scipy build being used from a quick look at google results, but again I wouldn't know much about Win environments.

**Comment by jmschrei** [comment]
Can you try pinning the requirement to Cython=0.25.0 and see if it runs? You'll need to update the dev-requirements.txt and the setup.py file.

**Comment by fortiema** [comment]
Seems like it's not making any difference.

**Comment by fortiema** [comment]
Reverted last commit. I've seen the other open PR also fails the 3.4 appveyor build as well.

**Comment by jmschrei** [comment]
Yeah this doesn't seem like an issue on your part. Gonna go ahead and merge, thanks for the contribution.

**Comment by jmschrei** [comment]
Actually, would you mind updating the docs/whats_new.rst file with this quick fix? It should be under the 0.8.2 changes on the top.

**Comment by fortiema** [comment]
Sure thing, just did. BTW I noticed some dependencies are missing to be able to build the docs (sphinx, sphinx_rtd_theme, mock). Would probably be better to add it to dev-requirements.txt. I can submit a PR for that as well later.

**Comment by jmschrei** [comment]
Great! I'll merge once the other tests pass.

**Comment by jmschrei** [comment]
Thanks for the contribution!

**Pull request merged**
