### PR TITLE
DOCS fixes code-block in installation

### LINKED ISSUE #379: Missing answer in installation FAQ
In the installation FAQ [here](https://pomegranate.readthedocs.io/en/latest/install.html) the second question has an incomplete answer. Should be an easy fix for whoever meant to write the answer the first time.

### PR DESCRIPTION
**Pull request by luisminero**
Fixes #379 

Added a blank line before the bash code in the Installation page of the documentation.
Also fixed two other code-blocks.

### CODE REVIEW

**Comment by luisminero** [comment]
The AppVeyor build failed because of the one hour time limit, the Travis one passed. I didn't change anything very complex, should be easy to review these commits. Thanks.

**Comment by jmschrei** [comment]
Hi @luisminero. What is the benefit of these newlines?

**Comment by luisminero** [comment]
Hi @jmschrei. There needs to be a newline after a code-block directive, to display the code correctly in the documentation. I tested the docs locally before submitting this PR. Thanks.

These are the docs, for reference:
http://www.sphinx-doc.org/es/stable/markup/code.html#directive-code-block

**Comment by jmschrei** [comment]
Ah I see, thanks. What is the purposes of splitting up the paragraphs that are just text?

**Comment by luisminero** [comment]
In the commit e54640d?, because before them come reStructuredText directives, and need a newline also. I think, sorry on this one, almost sure that's why I did that.

**Comment by jmschrei** [comment]
If you can merge those back into paragraphs I'll go ahead and merge this in.

**Comment by jmschrei** [comment]
I went ahead and made the changes in the callback PR. thanks for pointing them out!

**Comment by luisminero** [comment]
Thanks, now I remember that when I was fixing the typo I separated the sentences to see the source file better. Other than that, the splitting of the paragraphs doesn't have any purpose, but it doesn't change the output, like in LaTeX.

**Pull request closed without merging**
