### PR TITLE
Add linux aarch64 wheel build support

### PR DESCRIPTION
**Pull request by odidev**
Add linux aarch64 wheel build support. 
Related to https://github.com/jmschrei/pomegranate/issues/931 @jmschrei Could you please review this PR?

### CODE REVIEW

**Comment by jmschrei** [comment]
Isn't this only going to produce builds on aarch64?

**Comment by jmschrei** [comment]
I'm not sure that this workflow is working. There only seems to be one set of jobs spawned, not two (one for aarch64 and one for x86). Can you clarify?

**Comment by jmschrei** [comment]
Oh, sorry, this is editing the other workflow. Is it possible to modify the "build" workflow first so I can see it in action?

**Comment by odidev** [comment]
> Is it possible to modify the "build" workflow first so I can see it in action?

I have tried to modify the build workflow for aarch64. It looks that the flake8 command is failing for aarch64 in my forked repository but locally it is passing for aarch64 for your repository. Could you please suggest some pointers? 

**GHA Logs:** https://github.com/odidev/pomegranate/runs/4088748735?check_suite_focus=true

**Comment by odidev** [comment]
@jmschrei Could you please review this PR? Thanks in advance.

**Comment by jmschrei** [comment]
Thank you for your contribution. However, pomegranate has recently been rewritten from the ground up to use PyTorch instead of Cython, and so this PR is unfortunately out of date and will be closed.

**Pull request closed without merging**
