### PR TITLE
Eliminate unnecessary variables X_int and X_int_ptr

### PR DESCRIPTION
**Pull request by alexhenrie**
In MarkovNetwork, `X_int` is not used at all and does not appear to be in any way necessary to calculate.

### CODE REVIEW

**Comment by jmschrei** [comment]
When using `nogil` you need to pass a pointer to the data rather than the numpy array itself, which can cause problems. I agree that the code block isn't used for MarkovNetwork, so I've removed it on my end. Thanks!

**Comment by alexhenrie** [comment]
> When using `nogil` you need to pass a pointer to the data rather than the numpy array itself, which can cause problems.

I don't know what you mean by this comment. The point of the change was to not use numpy at all for this variable. `X_int` will remain allocated for the entire duration of the `with nogil` section; it cannot be deleted until the function completes. What am I missing?

**Comment by jmschrei** [comment]
You changed `(<Model> self.distributions_ptr[i])._summarize(X_int_ptr, weights_ptr, n, 0, 1)` to `(<Model> self.distributions_ptr[i])._summarize(X_int, weights_ptr, n, 0, 1)`. I'm saying that the nogil function expects a C pointer, not a numpy array.

**Comment by alexhenrie** [comment]
Right. I also changed `X_int` from a numpy array to a C pointer.

**Comment by jmschrei** [comment]
Oh, I missed that. Well-- I already made the MarkovNetwork change on my end, which seems like the bigger contribution. Sorry about the confusion.

**Comment by alexhenrie** [comment]
I'll rebase this and open a new pull request.

**Pull request closed without merging**
