### PR TITLE
Deprecation warning YAMLLoadWarning: Add Loader argument for yaml loading

### PR DESCRIPTION
**Pull request by m-martin-j**
Small change made, in order to deal with deprecation warning: YAMLLoadWarning, when calling from_yaml e.g. for an HMM instantiation from yaml string
"default loader is unsafe" so I offer to replace it by yaml.Loader,
(see also https://msg.pyyaml.org/load)
(one of my first pull requests, plz be gentle =))

### CODE REVIEW

**Comment by m-martin-j** [comment]
Haven't executed tests but it checks out for instantiating an hmm from yaml

**Comment by jmschrei** [comment]
Thanks for catching this. Can you test whether the SafeLoader would work as well? Might as well improve the safety if it doesn't effect performance.

**Comment by m-martin-j** [comment]
Reasonable though; done. Using yaml.SafeLoader took only 0.00021 longer compared to using yaml.Loader on my i7-6700 (for an hmm from the first 6 cells of [this example](https://github.com/jmschrei/pomegranate/blob/master/tutorials/B_Model_Tutorial_3_Hidden_Markov_Models.ipynb)).

Tests ran through, too.

```
----------------------------------------------------------------------
Ran 457 tests in 16.364s

OK
```

**Comment by jmschrei** [comment]
Thanks again!

**Comment by m-martin-j** [comment]
Pleasure

**Pull request merged**
