### PR TITLE
Add test for hmm using gmm from_json

### PR DESCRIPTION
**Pull request by jkleckner**
This patch set allows GeneralMixtureModels to be used with
HiddenMarkovModel.from_json() and adds a test.

It is a bit of a mystery why the GeneralMixtureModel class is not in
scope already.

### CODE REVIEW

**Comment by jkleckner** [comment]
@jmschrei would you please look into the test failure to see if something obvious in the process is wrong?

**Comment by jmschrei** [comment]
Nice, thanks for the contribution. I'm guessing the issue is that the weights are stored as the log weight instead of the actual value. Let me see.

**Comment by jmschrei** [comment]
I think this needs to be changed to `numpy.exp(self.weights).to_list()`: https://github.com/jmschrei/pomegranate/blob/master/pomegranate/gmm.pyx#L424

**Comment by jmschrei** [comment]
Same here, actually: https://github.com/jmschrei/pomegranate/blob/master/pomegranate/NaiveBayes.pyx#L86

**Comment by jmschrei** [comment]
I think the right thing to do is for me to make a self.weights and a self.log_weights and use them appropriately-- but this will be a quick fix that will solve people's issues.

**Comment by jkleckner** [comment]
@jmschrei Then you might want to take over this patch set?

**Comment by jkleckner** [comment]
@jmschrei I amended the patch with those two fixes and the test now passes.

**Comment by jmschrei** [comment]
Awesome, thanks!

**Pull request merged**
