### PR TITLE
Fix memory leak

### PR DESCRIPTION
**Pull request by fcaldas**
Adds 4 frees to the end of _viterbi() function clearing allocated memory

### CODE REVIEW

**Comment by jmschrei** [comment]
There are a large number of aesthetic changes here as well removing white space. Can you get rid of those and just add in the free lines?

**Comment by fcaldas** [comment]
Sure, I forgot to disable a plugin that removes trailing whitespaces, sorry

**Comment by fcaldas** [comment]
Also, there is a return in the middle of the call for _viterbi() function, so I added a few calls for free() just before.

**Comment by jmschrei** [comment]
Great, thanks!

**Pull request merged**
