### PR TITLE
Switch to pytest from unsupported nose

### PR DESCRIPTION
**Pull request by mr-c**
We need this for Debian as nose isn't working with Python 3.11

https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=1024045

### CODE REVIEW

**Comment by jmschrei** [comment]
Oh, great, thanks! Unfortunately, I'm in the middle of rewriting pomegranate using torch and the unit tests for that are being written in pytest. I don't have the time to continue to develop pomegranate separate from that rewrite. I am anticipating that the first public release will be next week. 

btw I had been using the nose assert functions with pytest but here you remove them. I haven't actually checked with py3.11 yet -- is the nose module in its entirety broken?

**Comment by mr-c** [comment]
> Oh, great, thanks! Unfortunately, I'm in the middle of rewriting pomegranate using torch and the unit tests for that are being written in pytest. I don't have the time to continue to develop pomegranate separate from that rewrite. I am anticipating that the first public release will be next week.

Okay. These patches work for us, so maybe another distribution will find them useful.

> btw I had been using the nose assert functions with pytest but here you remove them. I haven't actually checked with py3.11 yet -- is the nose module in its entirety broken?

Yeah, `nose` is relying on `getargspec` being in the `inspect` module, but that is no longer there for Python 3.11 (it was deprecated in Python 3.0)
```
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/nose/suite.py", line 209, in run
    self.setUp()
  File "/usr/lib/python3/dist-packages/nose/suite.py", line 292, in setUp
    self.setupContext(ancestor)
  File "/usr/lib/python3/dist-packages/nose/suite.py", line 315, in setupContext
    try_run(context, names)
  File "/usr/lib/python3/dist-packages/nose/util.py", line 453, in try_run
    inspect.getargspec(func)
    ^^^^^^^^^^^^^^^^^^
AttributeError: module 'inspect' has no attribute 'getargspec'
```

Given that `nose` has had no [releases since 2015](https://pypi.org/project/nose/#history) and [no commits since 2016](https://github.com/nose-devs/nose/commits/master) I don't expect to ever have a `nose` release with Python 3.11 compatibility

**Comment by jmschrei** [comment]
Got it. Thanks for the info and for taking the time to help me out by rewriting these tests.

**Comment by jmschrei** [comment]
Thank you for your contribution. However, pomegranate has recently been rewritten from the ground up to use PyTorch instead of Cython, and so this PR is unfortunately out of date and will be closed.

**Pull request closed without merging**
