### PR TITLE
addressing the to/from json issues

### PR DESCRIPTION
**Pull request by shpigi**
Hi
This code modification will flatten the to/from json serialization procedure (issue 12)
It also fixes the MultivariateGaussianDistribution serializarion (issue 14) 
I also corrected the naming of IndependentCompunentsDistribution which was wrong (assigned  the name 'MultivariateDistribution')

Hope you like it.

Lavi

### CODE REVIEW

**Comment by jmschrei** [comment]
A lot of this looks good. Is there a reason you removed the majority of JSON formatting for the file? I feel as though it may make those files unreadable with no benefit.

**Comment by shpigi** [comment]
well, on my screen (using ipython qtconsole on linux) it looks better without the formatting:
```
In [2]: model.to_json()
Out[2]: '{"end": {"distribution": null, "class": "State", "weight": 1.0, "name": "ExampleModel-end"}, "name": "ExampleModel", "distribution ties": [], "silent_index": 1, "end_index": 1, "states": [{"distribution": {"frozen": false, "class": "Distribution", "parameters": [0.0, 1.0], "name": "UniformDistribution"}, "class": "State", "weight": 1.0, "name": "uniform"}, {"distribution": null, "class": "State", "weight": 1.0, "name": "ExampleModel-end"}, {"distribution": null, "class": "State", "weight": 1.0, "name": "ExampleModel-start"}], "start": {"distribution": null, "class": "State", "weight": 1.0, "name": "ExampleModel-start"}, "edges": [[0, 1, 1.0, 0.5, null], [2, 0, 1.0, 0.5, null]], "class": "HiddenMarkovModel", "start_index": 2}'
```

compared with:
```
In[3]: json.dumps(json.loads(model.to_json()),separators=(',', ' : ' ), indent=4 )
Out[3]: '{\n    "end" : {\n        "distribution" : null,\n        "class" : "State",\n        "weight" : 1.0,\n        "name" : "ExampleModel-end"\n    },\n    "name" : "ExampleModel",\n    "distribution ties" : [],\n    "silent_index" : 1,\n    "end_index" : 1,\n    "states" : [\n        {\n            "distribution" : {\n                "frozen" : false,\n                "class" : "Distribution",\n                "parameters" : [\n                    0.0,\n                    1.0\n                ],\n                "name" : "UniformDistribution"\n            },\n            "class" : "State",\n            "weight" : 1.0,\n            "name" : "uniform"\n        },\n        {\n            "distribution" : null,\n            "class" : "State",\n            "weight" : 1.0,\n            "name" : "ExampleModel-end"\n        },\n        {\n            "distribution" : null,\n            "class" : "State",\n            "weight" : 1.0,\n            "name" : "ExampleModel-start"\n        }\n    ],\n    "start" : {\n        "distribution" : null,\n        "class" : "State",\n        "weight" : 1.0,\n        "name" : "ExampleModel-start"\n    },\n    "edges" : [\n        [\n            0,\n            1,\n            1.0,\n            0.5,\n            null\n        ],\n        [\n            2,\n            0,\n  
```

Most places where I see json used, usually in client-server applications, the formatting is conventionally left out, perhaps to save bandwith or screen space or because it is assumed that json is the information and pretty printing is someone else's job. 
Anyway, one could easily get back the pretty printed version by parsing and and re-writing the json as I  have just done above. (This, by the way, would have been more difficult before my code change because of the strings within strings thing) .

**Comment by jmschrei** [comment]
The output to the screen is not going to look as good, but output to a text file will look significantly better. Since we're using to_json to print directly to a file, that was my motivation. Maybe a good merger would be to take in an optional filename, and if that's provided, add in the formatting, otherwise don't?

**Comment by shpigi** [comment]
Sure. That's possible. I like even better having the option of choosing.  We could have the to_json functions accept the `indent` and `separator` parameters which, if provided, be passed to control the nested 'dumps' calls.  That way you leave the redirection to file to the user's discretion.

**Comment by jmschrei** [comment]
I agree, that sounds better. Can you modify your PR to include that, and remove the commented code?

**Comment by shpigi** [comment]
sure

**Comment by jmschrei** [comment]
I will look at this tomorrow, since I've finished the Bayes net training additions.

**Comment by shpigi** [comment]
- modified the PR as agreed so that `indent` and `separators` can be provided to `to_json()' for all the objects.
- removed commented code
- updated my version to current master (2.0.8)

**Comment by jmschrei** [comment]
Hi @shpigi 

I have not merged this pull request because I have been rewriting the distributions part of the module for the last ~2 months to get it closer to C level. This is resulting in huge speed ups in training and calculating log probabilities. However, it is changing the API, making your great changes incompatible.

Sorry for the delay, but I'll make sure to make sure these all work before merging my branch.

If this is okay with you, I will close this PR.

**Comment by shpigi** [comment]
Hi. Sure. 
In any case, I hope you will continue to support some form of serialization. 
Thanks for the enhancements so far.
Lavi

**Comment by jmschrei** [comment]
Serialization is very important. I'm aiming to have the backend changes be back-compatible, so hopefully when it's merged the issues you raised should be fixed as well.

**Pull request closed without merging**
