### PR TITLE
Foundation for Structural Optimization of the HMM topology

### PR DESCRIPTION
**Pull request by Narsail**
See #188

### CODE REVIEW

**Comment by jmschrei** [comment]
What is the difference between splitting a state and turning it into a mixture of the two distributions with priors corresponding to the relative likelihood of going to each state?

**Comment by Narsail** [comment]
The idea is to give you a tool to optimize the structure of the HMM. I.e. in speech recognition the pronunciation of the letter "i" can be different from person to person. The Distribution mixture for every state will stay the same in kind and numbers (in speech recognition you work with a fixed number of features which will be represented by the Distribution of the state). So if you want to represent different pronunciations in one HMM you need to refine the structure and therefore the number of states and edges. The splitting of a state gives you a simple approach to extend that network. 

Btw. pulled the forked repository via pip into my project but can't find my methods (i pulled directly the commit). Do you know why this might happen?

**Comment by jmschrei** [comment]
I guess what I'm asking is what is the difference between splitting the state into two with the same in-out states and just replacing the distribution of that state with a mixture of the two distributions, with the prior probability over each distribution representing the difference in probabilities that the edges would've represented.

**Comment by Narsail** [comment]
In a simple left to right structure it makes sense to create a mixture distribution if you only want to split one state but if you want to build a new path through the hmm only working with the priors and mixture models won't work. So considering the splitting step isolated it can be done through mixture distributions. If you want to train a model, i.e. do multiple splits and then work with fitting and pruning to build a new structure, you need to split states.

**Pull request closed without merging**
