### PR TITLE
Define other_variables as a list rather than a dict

### PR DESCRIPTION
**Pull request by alexhenrie**
Using a list here makes it a little more clear that all of the indices are contiguous.

### CODE REVIEW

**Comment by jmschrei** [comment]
Won't this be wrong for all entries after `j == i`?

**Comment by alexhenrie** [comment]
Ah shoot, I missed that detail. Good catch.

**Comment by alexhenrie** [comment]
No wait, the if clause just makes the tuple at that index smaller. The entries in the list are definitely numbered continuously from 0 through d-1.

**Comment by alexhenrie** [comment]
This sort of confusion is exactly why it should be a list :P

**Comment by jmschrei** [comment]
Got it. I'm not going to merge this, though, because I'm not fond of handling small PRs like this. I don't want to encourage people to submit aesthetic PRs that don't reduce the line count or change the functionality.

**Pull request closed without merging**
