### PR TITLE
Add support for serialization in GMM and HMM

### PR DESCRIPTION
**Pull request by pixelou**
This PR follows up issue https://github.com/jmschrei/pomegranate/issues/153

It adds the methods `__getstate__` and `__getstate__` to GeneralMixtureModel and HiddenMarkovModel to make them 'picklable'.

I had to modify the automatic name generation of State to make sure we always have unique state names (unless overriden by user). Otherwise, deserialization fails on name collision. This fix relies on the uuid library which is part of python standard library.
There are two very simple regression tests to check that pickle doesn't crash. I didn't test if the reloaded value is identical to the original one because json tests should be sufficient. And I have no clue how to properly compare the objects :-) .

### CODE REVIEW

**Comment by pixelou** [comment]
Ok, there is a small mistake in the tests, but that is not all. It seems python 2.7 is not as good as 3.* for pickling. Even simpler types such as DiscreteDistribution cannot be converted, I have to investigate this a bit deeper.

**Comment by jmschrei** [comment]
Thanks for the contribution, and for looking into it for me! I'm eager to see what you find. Keep in mind that all objects are cython extension objects with pointers as private attributes. I don't know if this makes things more difficult, but I thought I'd let you know. In this sense, DiscreteDistribution is in fact one of the more complicated objects because even though the python side is just a dictionary, the cython side is several pointer arrays used for speedy training.

**Comment by pixelou** [comment]
After further reading, I found that extension classes need to provide the `__reduce__` method instead of `__getstate__` and `__setstate__`  [http://ask.sagemath.org/question/8376/pickling-extension-classes/](http://ask.sagemath.org/question/8376/pickling-extension-classes/). `__reduce__` requires to add a function at the module level to process the reduced representation. Unfortunately, static methods or class methods are not allowed.  Is it ok if I add a `_deserialize` function in the modules?

**Comment by jmschrei** [comment]
Sure, go ahead. I may end up renaming or restructuring it in the future to be more consistent with the API of the entire module, but it's more important to get something working right now. Thanks again for your efforts.

**Comment by pixelou** [comment]
Modifications don't break the library anymore. There are still a few more models to do.

**Comment by pixelou** [comment]
I'm going to leave the finite state machines and the factor graphs untouched because I am not familiar with these two and there are no serialization tests to build on.

Using serialization, it should be easy to propose a default `__deepcopy__` method in `Distribution` and `Model` to inherit from:

```python
    def __deepcopy__(self, memo):
        return pickle.loads(pickle.dumps(self))
```

That should in turn allow the use of pomegranate models in scikit-learn tools such as GridSearchCV.

**Comment by jmschrei** [comment]
Thanks for this great work. I'll review it ASAP

**Comment by jmschrei** [comment]
This looks great. Thanks for adding in unit tests as well. Would you mind squashing the commits to be a single one? Also, does this make the code compatible with GridSearchCV, or do I need to add the `__deepcopy__` method? 

HMM needs the `__getstate__` and `__setstate__` methods because converting it to/from JSON is more complicated than just using the constructor, right? The other models can just pass a list of parameters to feed into the constructor, but HMMs have structure?

**Comment by pixelou** [comment]
I will look into git doc for commits squashing.

Unfortunately, I don't think supporting  GridSearchCV cleanly is going to be completely straightforward. The documentation on the estimator interface ([here](http://scikit-learn.org/stable/developers/contributing.html#rolling-your-own-estimator)) mentions the `get_params` and `set_params` that also need to be implemented. As I read the doc more carefuly, it's probably necessary to implement `clone` explicitely as well. The standard `__deepcopy__` is more like a fallback. To conclude on this point, I imagine the simplest solution is to implement the standard `__deepcopy__` using the simple solution based on pickle, and have the `clone` as an alias to comply with the estimator interface. I think it can be done by just modifying `Model` and `Distribution` base classes.

About the HMM: Actually, I didn't use Json methods for any of the distributions and models because JSON serialization uses class methods and pickle serialization relies on instance methods. The way I understand the pickle documentation ( and StackOverflow ;-) ) it's easier to simply have the constructor rebuild the object in most cases. If the constructor is not enough, as it is for HMMs, `__setstate__` (and its friend `__getstate__`) is the standard way to do the extra work.

**Comment by jmschrei** [comment]
LGTM, I'm gonna merge it.

**Pull request merged**
