### PR TITLE
Small fixes and corrections for tutorials, mainly for Python 3 

### PR DESCRIPTION
**Pull request by reckoner**
Small fixes and corrections for tutorials, mainly for Python 3.

### CODE REVIEW

**Comment by jmschrei** [comment]
Thanks for the contribution. Unfortunately I can't really see the diffs clearly because of jupyter notebooks. Can you briefly describe the types of fixes?

**Comment by reckoner** [comment]
Broken print statements for Python 3. Some missing variables and typos in the text. 

https://github.com/jupyter/nbdime

Can diff the notebooks for you.

**Comment by jmschrei** [comment]
Sounds good. Thanks for the contribution!

**Comment by jmschrei** [comment]
Looks like there may have been an issue in the PR. The A_Overview.ipynb and B_Model_Tutorial_1_Distributions.ipynb files weren't recognized as JSON anymore. Some of the other notebooks weren't displaying their output. If you wouldn't mind, can you submit another PR where all the notebooks are displaying their output as well? That'll be helpful for people trying to view them on GitHub. Thanks!

**Pull request merged**
