### PR TITLE
Add to_yaml convenience functions

### PR DESCRIPTION
**Pull request by jkleckner**
YAML is a superset of JSON that is 4 to 5 times more compact which makes
it easier to inspect visually.  To use it you have to make sure the yaml
package is installed.

### CODE REVIEW

**Comment by jmschrei** [comment]
Thanks for the functions! This seems like a good thing to have. Is it possible to add a test for each model? You can probably copy the `to_json` and `from_json` unit tests for each model but use `to_yaml` and `from_yaml` instead.

**Comment by jkleckner** [comment]
I intentionally didn't create a `from_yaml` because I wasn't sure that it would be as reliable as `from_json`.

Json serialization/deserialization is heavily relied on and I almost don't want to encourage people to use yaml for anything other than human readability.  I may be too cautious, though, since yaml is also widely used.

**Comment by jmschrei** [comment]
How difficult would it be to add in a from_yaml method? One benefit of including many deserialization techniques is that it makes pomegranate integrate more with other packages or programs that may use that serialization/deserialization scheme

**Comment by jkleckner** [comment]
The lazy way I layered it on top of `to_json` means that the same trivial thing could be done for `from_json`.  Specifically just read the `YAML`, convert to `JSON`, then call `from_json`.

I suppose tests could be done that way leveraging the existing `JSON` data as a reference.

**Comment by jmschrei** [comment]
I think it would be helpful to have a `from_yaml` format as well and to include a test. I can also imagine a situation in which someone writes out a model, uses the yaml format due to its readability, tweaks it manually, and would like to read it back in.

**Comment by jkleckner** [comment]
That failure was an example of the whitespace conflict resolved in #445 ...
Once rebased that should be a lot better...

**Comment by jkleckner** [comment]
I force-pushed a branch that should have resolved the conflict on whitespace.  I don't understand why github is still showing a conflict.

**Comment by jkleckner** [comment]
I resolved the wrong line - now testing.

**Comment by jmschrei** [comment]
Looks good! I'm fine with the pyyaml requirement, it seems easy enough to install.

**Comment by jmschrei** [comment]
Looks like this killed the autodocs. We needed to add `pyyaml` to the `dev-requirements.txt` file as well.

**Pull request merged**
