### PR TITLE
Bug fix when instantiating naive Bayes model `from_samples` using `DiscreteDistribution`

### PR DESCRIPTION
**Pull request by hylkedonker**
As described in [#840], when instantiating a naive Bayes model composed of `DiscreteDistribution`s (i.e., `NaiveBayes.from_samples(DiscreteDistribution,..)`) the categories are not correctly fit to the data. The problem derives from `IndependentComponentsDistribution`, which immediately calls `_summarize` when the possible characters/categories to summarize are yet unknown.
At least two possible scenarios are possible to resolve this:
1) Make a pass over the entire data to collect all the unique characteres, and subsequently count the values, or
2) Make a single pass over the data and add keys to the `summaries` dict  as they are observed.
This pull request implements solution 2, plus an accompanying unit test.

In addition, this pull request contains a small commit that allows `DiscreteDistribution`s to be fit to `n x 1` vectors in addition to  flat arrays (such as lists and tuples).

### CODE REVIEW

**Comment by hylkedonker** [comment]
I have updated the code a little bit, because `NaiveBayes.predict_proba` would return `NaN` despite a successful fit of the parameters. It is fixed in the current version, and I have expanded the unit test accordingly.

**Comment by jmschrei** [comment]
Thanks for the PR! I'll take a look through it this week -- please ping me if you haven't heard back from me by Friday.

**Comment by hylkedonker** [comment]
Great, will do!

**Comment by hylkedonker** [comment]
Hi Jacob,
Hereby the ping! :-)

**Comment by jmschrei** [comment]
Thanks for pinging me. Sorry about not getting to it-- this last week has
really gotten away from me. I'll try (very hard) to look at it this weekend.

**Comment by hylkedonker** [comment]
Hi Jacob,
Any ideas when you might have time to look at the pull request?
Thanks!
Hylke

**Comment by jmschrei** [comment]
Hey, sorry for the delay. I took the holidays off and am currently trying to catch up. I was able to migrate pomegranate from TravisCI/appveyor over to GitHub actions for unit testing and deployment, so that should fix some of the build issues that have come up. I'll try to get back to your PR by next week.

**Comment by jmschrei** [comment]
Everything looks good. Thanks!

**Pull request merged**
