### PR TITLE
Ipynb fixes

### PR DESCRIPTION
**Pull request by jkleckner**
Note that it may be a regression that the list of states/nodes can't be passed in.  If that is fixed, then those changes here aren't needed.

### CODE REVIEW

**Comment by jkleckner** [comment]
A nice goal for the next release would be to achieve a clean `make nbtest`

**Comment by jmschrei** [comment]
Yes it would. I've been meaning for a while to rewrite a lot of the tutorials to make them cleaner and focus on more recent features. This will be a good guide to help. Thanks for your contributions!

**Comment by jkleckner** [comment]
My apologies for the churn in this patch set. I'm used to a rebase rather than merge style.  I will rebase this to master then stop fiddling...

**Comment by jmschrei** [comment]
I'm not sure what's up with Travis, but it seems to be disconnecting a lot on one build in particular...

**Pull request merged**
