### PR TITLE
beautify kmeans and MarkovChain

### PR DESCRIPTION
**Pull request by pixelou**

### CODE REVIEW

**Comment by jmschrei** [comment]
Great. All of the files should have a single line at the end though (I might've missed this for base), can you add that and then I'll merge?

**Comment by pixelou** [comment]
Forgot to check that indeed. Fixed now.

**Comment by jmschrei** [comment]
LGTM

**Comment by jmschrei** [comment]
Thanks for the help with this. I think the best next place would be gmm and Naive Bayes, as I don't think I'll be touching those for a while.

**Pull request merged**
